# 基础镜像: RUST-ALPINE3.14
FROM rust:1.57.0-alpine3.14
LABEL maintainer="jxz_211@163.com"
# 修改可重构镜像，防止镜像分层缓存
ENV FRESHED_AT 2020-12-30
# 开发环境参数
ENV RUST_ENV="development"
# 工作目录
WORKDIR /usr/share/www
# 将入口脚本写入
ADD ./docker-entrypoint.sh /usr/share/docker-entrypoint.sh
# 增加脚本权限
RUN chmod u+x /usr/share/docker-entrypoint.sh
# 安装时区数据
RUN apk add --no-cache tzdata
# 安装rust编译的基础依赖
RUN apk add build-base 
# 判断是否开发环境
RUN if [ "${RUST_ENV}" != "production" ]; then cargo install cargo-watch; fi
# 命令行
ENTRYPOINT [ "/usr/share/docker-entrypoint.sh" ]