# 基础镜像: Centos 7.0
FROM centos:7
LABEL maintainer="jxz_211@163.com"
# 修改可重构镜像，防止镜像分层缓存
ENV FRESHED_AT 2020-04-27
# 安装node
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash \
    && yum -y install nodejs
# 进入
ENTRYPOINT [ "node" ]
# 执行命令
CMD [ "--version" ]
